### ISSUE TITLE
Objects don't always spawn

### ISSUE THREAD

**Issue by HALALsnackbar** [Mobius1/esx_collectables#2]
So I was getting reports from some of my users that sometimes collectables aren't spawning and I did teleport to a spot they were claiming didnt work and sure enough there was no collectable.

However when I restarted the script it appeared. I tried lowering the draw distance from 50 > 25 but I'm still getting some reporting this issue.

**Comment by Mobius1** [comment]
Are the collectables the default ones included with this repo or are they custom ones that you've added?

**Comment by HALALsnackbar** [comment]
Yes the default ones. I have changed only the draw distance but otherwise the script is untouched. I know there is one person who cant see ANY objects at all.


Great script by the way. As a work around I added a command that runs the RemoveItems() and Initialize() functions which essentially allows each client to "refresh" the collectables.

**Comment by jananpatel2002** [comment]
@Mobius1 I am one of the people in HAL's city that is having the issue. I have tried everything, from clearing cache, lowering every setting possible, and removing all my mods. We have restarted the script many times also. I see none of the objects.

**Comment by Mobius1** [comment]
Check the row in your database or the progress menu to see if it has you as collected them all. There was a bug that caused this, but I'm sure it was fixed.

**Comment by jananpatel2002** [comment]
> Check the row in your database or the progress menu to see if it has you as collected them all. There was a bug that caused this, but I'm sure it was fixed.

I can assure you that the progress bar says 0/50 for spaceship parts (the ones I’m looking for currently). I have also tried resetting the counter and it’s still the same issue

**Comment by Mobius1** [comment]
I've set collectable entities as mission entities to prevent them from being removed by the game engine and pushed it to a new release. It may or may not fix your problem.

[v1.1.2](https://github.com/Mobius1/esx_collectables/releases/tag/1.1.2)

**Comment by HALALsnackbar** [comment]
I deployed your fix on my server and @jananpatel2002  and so far every collectable he's checked has been there. Looks like this may have resolved the issue.
